swagger: '2.0'
info:
  title: mDNS API
  description: Rest API for mDNS Server
  version: 1.0.0
  contact:
    email: cryptocoin62@gmail.com
host: localhost
basePath: /
schemes:
  - http
paths:
  /dns:
    get:
      tags:
        - list
      summary: Show all dns records
      operationId: show_dns_records
      responses:
        '200':
          description: OK
          schema:
              $ref: "#/definitions/dns_records"
        '400':
          description: Bad request
          schema:
            $ref: "#/definitions/answer"
    post:
      tags:
        - add
      summary: Add dns entry
      operationId: add_dns_entry
      consumes:
        - "application/json; charset=utf-8"
      produces:
        - "application/json; charset=utf-8"
      parameters:
        - in: body
          name: add
          required: true
          schema:
            $ref: '#/definitions/dns_entry'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/dns_entry'
        '400':
          description: Bad request
          schema:
            $ref: "#/definitions/answer"
    put:
      tags:
        - update
      summary: Update dns entry
      operationId: update_dns_entry
      consumes:
        - "application/json; charset=utf-8"
      produces:
        - "application/json; charset=utf-8"
      parameters:
        - in: body
          name: update
          required: true
          schema:
            $ref: '#/definitions/dns_entry'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/dns_entry'
        '400':
          description: Bad request
          schema:
            $ref: "#/definitions/answer"
    delete:
      tags:
        - delete
      summary: Delete dns entry
      operationId: delete_dns_entry
      parameters:
        - in: body
          name: delete
          required: true
          schema:
            $ref: '#/definitions/dns_entry'
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/answer"
        '400':
          description: Bad request
          schema:
            $ref: "#/definitions/answer"
  /dns/{id}:
    get:
      tags:
        - show
      summary: List one dns entry
      operationId: list_one__dns_entry
      parameters:
        - in: path
          name: id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: "#/definitions/dns_entry"
        '400':
          description: Bad request
          schema:
            $ref: "#/definitions/answer"
definitions:
  dns_records:
    type: object
    additionalProperties:
      $ref: "#/definitions/dns_entry"
  dns_entry:
    type: object
    properties:
      domain:
        type: string
      ipv4:
        type: string
      ipv6:
        type: string
      dkim:
        type: array
        items:
          type: string
      ips:
        type: array
        items:
          type: string
      acme:
        type: array
        items:
          type: string
      private_key:
        type: array
        items:
          type: string
      public_key:
        type: array
        items:
          type: string
  answer:
    type: object
    properties:
      Code:
        type: integer
        format: uint32
      Message:
        type: string