name: Release to Docker Hub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: login
    - uses: actions/checkout@v1
    
    env:
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: | 
        login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
        - name: build
        - uses: actions/checkout@v2
        run: docker build . --file Dockerfile --tag marlikalmighty/mdns:$(date +%s)
        
        - name: push
        - uses: actions/checkout@v3
        run: docker push ${{secrets.DOCKER_USER}}/mdns
          




